name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, zip, bcmath, gd, intl, mysql, sqlite3, xdebug
          coverage: xdebug

      - name: Install Composer
        run: sudo apt-get install -y composer

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install NPM dependencies
        run: npm install

      - name: Install PHP dependencies
        run: composer install

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate Laravel APP_KEY
        run: php artisan key:generate

      - name: Generate Passport keys
        run: php artisan passport:keys

      - name: Generate Database SQLite
        run: touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate:refresh

      - name: Build assets
        run: npm run build

      - name: Run tests
        run: php artisan test

      - name: Run tests
        run: XDEBUG_MODE=coverage php artisan test --coverage-clover=coverage.xml
